print("hello samar")
print("*")
print("**")
print("***")
print("****")
print("*****")
print("i dont know what to write")
print("     *")
print("    **")
print("   ***")
print("  ****")
print(" *****")
print("******")