print('whats your name' )
n=str(input())
print("hello", n)
print("WHICH PLACE ARE YOU IN?")
P=str(input())
print('hello',n,'how is the werather in',P,)
print('how old are you')
age=int(input())
print("good to know you are", age, 'years old')